### ISSUE TITLE
Bug: Empty Loading Area Increasing Scroll Height on Homepage

### ISSUE THREAD

**Issue by emsqr** [anishjoshi1999/CodeCareerNepal-Client#21]
# Description
When loading the homepage of the website, after scrolling down slightly, empty loading area appears for a certain period of time.

## Steps to Reproduce
1. Visit the homepage of the website.
2. Notice the increase in scroll height.
3. Scroll down slightly and observe the loading behavior.

## Expected Behavior
The loading area should not appear when scrolling down the homepage.

**Comment by anishjoshi1999** [comment]
@matrix-bro could you please look into it ?
